#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the index route is here since it does not need a controller, it can render template directly from route
welcome_index:
    path:          /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'welcome.html.twig'